### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by Amplifi-Beats** [vukani-dev/improvement-roll#1]
This app is a really great concept, I think it would benefit from a dark mode, white text and black/grey background. Will save battery on oled's and preserve eyesight everywhere. Amazing app!

**Comment by vukani-dev** [comment]
Thank you so much for the feedback!
I'm working on a update right now for polish and performance. A theme toggle will probably come out with that.

**Comment by Amplifi-Beats** [comment]
Cool, I'm very excited!

**Comment by vukani-dev** [comment]
Just added in new release! Enjoy, and let me know how it looks/ if there is any issues.
