### ISSUE TITLE
Export creates empty file

### ISSUE THREAD

**Issue by dylan-manchester** [vukani-dev/improvement-roll#10]
Device: Galaxy S7 Edge
OS: Andriod 8.0.0
App Permission for Storage is turned on

When exporting a category, a file is created with the correct extension but has no content as seen below.

![EmptyFile](https://user-images.githubusercontent.com/78382743/145895931-a639c121-e1c9-454d-82ff-e68441fd7194.jpg)

**Comment by vukani-dev** [comment]
I forgot to follow up on this, did this get fixed with the latest update?

**Comment by dylan-manchester** [comment]
Yes, thanks!
