### ISSUE TITLE
Cursor moves unexpectedly while editing text

### ISSUE THREAD

**Issue by Zocker1999NET** [vukani-dev/improvement-roll#16]
I found this bug so curious that I thought a video might be required:

https://user-images.githubusercontent.com/1645646/153234168-9a2fc6c1-98a6-4192-a040-4e18a3811a39.mp4

What I do in the video is:
- Edit the text `Meditate for 5|minutes` (`|` stands for the cursor; no space between `5` and `minutes`)
- Remove `5` with backspace, cursor ends up being not after but before the space now in between `for` and `minutes`: `Meditate for| minutes` (one space in between `for` and `minutes`
- Insert space, wait a few moments and cursor jumps back to the end of `for`: `Meditate for|  minutes` (two spaces in between `for` and `minutes`)
- Repeat typing space, ending up with `Meditate for|   minutes` (three spaces in between `for` and `minutes`)
- Insert `10` with keyboard, but because of a short moment in between typing `1` and `0`, in the text field then stands `Meditate for|01   minutes` with the cursor being again at the end of `for`
- Wait a few moments, cursor does not move

EDIT: clarified space length in embedded code sections because GitHub / the browser does not render multiple spaces enclosed in backticks: `2 spaces enclosed here: "  "`

(Maybe) good to know:
- Android 11 / Lineage OS 18.1
- used preinstalled AOSP keyboard in video & can confirm it also happens with AnySoftKeyboard
- have never seen this bug outside this app
- can confirm this bug happening on nearly every text field in this app, the title field of a task is not the only one
- does not happen if adding or removing characters at the very end of the text, e.g. `Meditate for 5 minutes|`

**Comment by vukani-dev** [comment]
Thank you for the feedback! This is a very strange issue....
I've looked into it and it boils down to the specific Kitten (UI library) Modal I'm using is causing it.
By replacing it with another Modal the issue resolves itself. So i'll work on doing that around the app and push out an update!

**Comment by vukani-dev** [comment]
The fix for this was released to the f-droid store. Can you confirm If the issue is still happening from your end? @Zocker1999NET

**Comment by Zocker1999NET** [comment]
Thanks for your work! I can confirm the issue is now resolved for me as well after updating to 1.2.7.
