### ISSUE TITLE
Add more logging to the logger 

### ISSUE THREAD

**Issue by vukani-dev** [vukani-dev/improvement-roll#23]
There is a logging util for the app found [here.](https://github.com/vukani-dev/improvement-roll/blob/main/utility_components/logging.component.js)
It allows logs to be printed to a file if debugMode is enabled.

Currently it is only used in a couple of places. Would be nice to expand this to other parts of the app.
A good place to start would be simply searching everywhere there is a console.log() call and adding a call to the logger with the same log.
Next would be looking for places where common things are being done, this could be error checking or parsing an object.

To add a call to the logger, import the utility at the top of the file:
`import * as logger from '../utility_components/logging.component.js';`

Then call it like so:
`logger.logDebug('User cancelled file picker');`

**Comment by zafar-hussain** [comment]
Hi @vukani-dev,

Please assign this issue to me, 

cheers

**Comment by vukani-dev** [comment]
@zafar-hussain All yours! Thank you! Lmk if you have any questions
