### ISSUE TITLE
Factor out categories into human-readable data-serialization format

### ISSUE THREAD

**Issue by simonsan** [vukani-dev/improvement-roll#3]
I think it would be nice to `import`/`export` categories and their tasks into/from a `yaml`/`toml` (as json is not as easy to write as those both) to add tasks + categories on a computer and then import them into the app.

**Comment by vukani-dev** [comment]
That's a great idea! I see you have a fork of the repo.
Is this something you had an interest in doing? If not, I can get to work on that now.

**Comment by simonsan** [comment]
> That's a great idea! I see you have a fork of the repo.
> Is this something you had an interest in doing? If not, I can get to work on that now.

Hey, glad you like it. Unfortunately I'm full of work for now, so just made the fork for convenience. Won't work on it anytime soon. :/

**Comment by vukani-dev** [comment]
Added in release 1.2 live now!
Gonna debug a little more just to be sure its solid before working on the next feature.

**Comment by simonsan** [comment]
> 
> 
> Added in release 1.2 live now!
> Gonna debug a little more just to be sure its solid before working on the next feature.

Nice! <3
