### ISSUE TITLE
Import of valid yaml and json file is not working

### ISSUE THREAD

**Issue by simonsan** [vukani-dev/improvement-roll#6]
Hey there,
I wanted to try the import feature and the app crashes everytime I'm trying to import valid yaml or json files. I can't even import the exported `general` category which I deleted and re-imported to test. Got it back by resetting the app state in the options though.

Can I do anything to help you diagnosing the error? Got a rooted phone and can open up a terminal. Any logfiles?

**Comment by vukani-dev** [comment]
Hello!
That's weird.. other than ensuring the app has permissions to read and write (which I'm sure you did) I cant think off the top of my head what would cause it to crash.
This also makes me wish I had a more elegant logging system for the app :(

Can you share the model of your phone? Also the Android the version? Is it crashing on file selection or on button press?
I will try my best to see if I can weed out the bug as I'm sure if its happening to you its happening to others.

**Comment by simonsan** [comment]
> app has permissions to read and write (which I'm sure you did)
Yep, double checked it - it does.

> Is it crashing on file selection or on button press?
It's crashing after switching back from choosing a file, after pressing the button to accept the file.

> Can you share the model of your phone?
Samsung Galaxy S5 (SM-G900F)

> Also the Android the version?
Android 11,
LineageOS 18.1-20210829-Nightly,
Kernel 3.4.113

**Comment by vukani-dev** [comment]
Hello! @simonsan 
I've released a new version of the app on the GitHub page under Releases (specifically 1.2.1)
This will add crash handling and should alert/write logs about what happened.
If you have time, download it and give it a try and see what you get.

**Comment by simonsan** [comment]
> Hello! @simonsan
> I've released a new version of the app on the GitHub page under Releases (specifically 1.2.1)
> This will add crash handling and should alert/write logs about what happened.
> If you have time, download it and give it a try and see what you get.

Is it on F-Droid as well? Didn't get any update notification 😬

**Comment by vukani-dev** [comment]
Not yet. It takes F-droid a couple of days to build the app and release it. I'd say sometime next week you should look for an update notification from them.

**Comment by simonsan** [comment]
> Error: Fatal: TypeError undefined is not an object (evaluating `'t.path.substr'`)

So @vukani-dev this is the error I'm getting after importing

**Comment by simonsan** [comment]
I'm importing it from my Nextcloud, so file paths have an `@` in it for the usernames for example. Maybe it has something to do with that, so it can't take a `substring` from the given path? @vukani-dev

**Comment by vukani-dev** [comment]
Thank you for your help!
When you say the YAML file has a bin property. What do you mean by that? I'm a little confused.  Would you mind sending me an example of one of the files you are trying to import? Maybe I can see why they are giving you problems and tweak the validation accordingly.

**Comment by simonsan** [comment]
> Thank you for your help!
> When you say the YAML file has a bin property. What do you mean by that? I'm a little confused. Would you mind sending me an example of one of the files you are trying to import? Maybe I can see why they are giving you problems and tweak the validation accordingly.

@vukani-dev You can copy this into `example.json`:

```
{
  "description": "A list containing positive activities",
  "key": 1,
  "name": "Activities",
  "time_sensitive": true,
  "tasks": [
    {
      "desc": "Example",
      "name": "Example",
      "time": 1
    }
  ]
}
```

And try to import it, it fails for me.

**Comment by vukani-dev** [comment]
Hello! Sorry it took me so long to get to this, last week was very busy on my end.
However, I think i know the issue. The importer just assumes you are sending in a JSON array rather than a single object.
Its an easy fix so ill finish that up and send the update through fdroid today!
Once again thank you for your help! If you encapsulate your JSON object in an array it should work until the update is live.

**Comment by simonsan** [comment]
> 
> 
> Hello! Sorry it took me so long to get to this, last week was very busy on my end. However, I think i know the issue. The importer just assumes you are sending in a JSON array rather than a single object. Its an easy fix so ill finish that up and send the update through fdroid today! Once again thank you for your help! If you encapsulate your JSON object in an array it should work until the update is live.

Great! <3 Just saying, I think it's not working for the YAML format either (TOML not sure), maybe for the same reason?

**Comment by simonsan** [comment]
With `encapsulating in an array` you meant the following, I guess?

```
[{
  "description": "A list containing positive activities",
  "key": 1,
  "name": "Activities",
  "time_sensitive": true,
  "tasks": [
    {
      "desc": "Example",
      "name": "Example",
      "time": 1
    }
  ]
}]
```

Because that doesn't work either for me :(

**Comment by vukani-dev** [comment]
![Screenshot from 2021-09-30 06-23-19](https://user-images.githubusercontent.com/65465868/135438440-d9077c2a-78c1-47f4-ad80-f76811b15bdc.png)
![Screenshot from 2021-09-30 06-24-08](https://user-images.githubusercontent.com/65465868/135438441-8a363b40-4fa5-4edd-b622-6b76fb419c72.png)
This is how I'm doing it which looks no different from yours (using v1.2.1 of the app) After the import you should see a small popup sayings its successful. Are there any logs being generated?

**Comment by simonsan** [comment]
> Are there any logs being generated?

Unfortunately not. It just shows "Error while selecting file. Only JSON, TOML, and YAML files are accepted.". I'm on `v1.2.2` now.

**Comment by simonsan** [comment]
> When you say the YAML file has a bin property. What do you mean by that?

With that I meant that the `raw mimetype` for `yaml` on my phone is `application/octet-stream` while for `json` it's `application/json`.

But I saw in your code, that you take the last `4 letters` of the filename and compare it. Maybe it has something to do with that?

**Comment by vukani-dev** [comment]
Ok I understand! Not exactly sure why the filetype checker is failing if your files have the correct suffix. But the idea of having a general parsing error logged sounds great. 

Also in reference to your previous post. I need to go through the app and add handled errors/validation to the logging system. Because there may be instances (especially as I'm looking to add new features) where a problem has occurred but my static error message response doesn't sufficiently capture what the real problem is. 

Some debug logging would be nice for this as well. However, I do want to be conscious of bloating up the filesystem. Maybe a toggle in settings for `debug mode` logging?

Either way ill clean up the importer codewise and add more logging so we can get to the bottom of this!

**Comment by simonsan** [comment]
Hey @vukani-dev, are there any news about this? I made a nice list for myself with `positive activities` and can't really use it in `improvement roll` although I would love to. :(

**Comment by vukani-dev** [comment]
@simonsan 
Hello! Sorry for the delay. The code is finished for this I just need test it and make an fdroid request for it.
I thought I could release it with some other feature I've been working on (sharing categories) but its taking me some time to get back to it.
I will cleanup today, so you should look for it on the store sometime next week!

**Comment by simonsan** [comment]
> @simonsan Hello! Sorry for the delay. The code is finished for this I just need test it and make an fdroid request for it. I thought I could release it with some other feature I've been working on (sharing categories) but its taking me some time to get back to it. I will cleanup today, so you should look for it on the store sometime next week!

Hey there, updated to the new version and importing works now 👍🏽 Thank you very much!

Some remarks:
- `Reset data` is not working, tap on it just does nothing
- For the imported category I need to activate "This category is split by time" manually, it doesn't seem to recognize it from the json-import although ` "time_sensitive": true` is set
