### ISSUE TITLE
Remarks on UI

### ISSUE THREAD

**Issue by simonsan** [vukani-dev/improvement-roll#8]
The "Reset data" button does not work for me, I wonder if it's because of the straight line on it maybe taking the focus? This is what the options menu looks like for me:
![Screenshot1](https://user-images.githubusercontent.com/14062932/141292289-474a7e9f-412a-49ce-b2b4-a8a36e3b4d00.png)

The "Re-Roll" button could be a bit wider I feel.
![Screenshot2](https://user-images.githubusercontent.com/14062932/141292291-3d1b15b6-60ef-42f2-bfdd-34cabc754549.png)

Thank you for the app!

**Comment by vukani-dev** [comment]
That's strange! Probably has to do with me adding magic numbers in places :smile: 
Should be easy to figure out though!

**Comment by vukani-dev** [comment]
@simonsan Took a while for approval but looks like the new version is out. Hopefully that resolves a couple of the UI issues you were having?

**Comment by simonsan** [comment]
Thanks for reminding me to close this, yes it does. :)
