### ISSUE TITLE
Textbox bug when creating new task

### ISSUE THREAD

**Issue by dylan-manchester** [vukani-dev/improvement-roll#9]
After typing `10 Push` into the task name, the following is rendered. The bug only appears to happen when letters are in the word, not sure why.

![Screenshot_20211201-010857_Improvement Roll](https://user-images.githubusercontent.com/78382743/144181504-cf6cc6eb-45ec-42dc-99d9-d7232938b4a8.jpg)

**Comment by vukani-dev** [comment]
This is interesting... None of my emulators/devices are able to reproduce this. 
I'm in the process of cleaning the style and code of this particular screen which will be out in the next small update.
Can you give me your Device and OS information?
Have you tried other keyboards?

**Comment by dylan-manchester** [comment]
Device: Galaxy S7 Edge
OS: Andriod 8.0.0
Keyboard: Samsung Keyboard 2.0.24.96
Have not tried with other keyboards since this is the first time something like this has ever happened with this keyboard

Notes for reproduction:
- Only occurs on user created categories (Not General category)
- Only affects the task name and description text boxes (Not category name or description)
- Does not happen when only typing numbers
- Still occurs after restart and redownload

**Comment by dylan-manchester** [comment]
Seems to be a React Native issue mainly with Galaxy phones.  My issue was resolved by disabling the "Predictive Text" in "Samsung keyboard settings"  

Based on this solution: https://github.com/facebook/react-native/issues/11068#issuecomment-317070904

The issue was very slightly different but seems to have the same root cause. Not sure if there is a good programmatic workaround for this right now.

**Comment by vukani-dev** [comment]
There's no harm in trying! I'll test it out to make sure it doesn't break anything and push it out with the code updates.

**Comment by vukani-dev** [comment]
@dylan-manchester Hey friend!
New update is out with the hacky fix. Want to try it out? 
I'm curious if it actually resolved your issue.

**Comment by dylan-manchester** [comment]
Hey! Just tested and it worked like a charm. Thank you!
